### PR TITLE
Update sdk and references

### PR DESCRIPTION
**Pull request by amerkoleci**
- Update to use10.0.17763.0 windows SDK.
- Update to stable 1.2.0 SharpGen.SDK and Runtime.

### CODE REVIEW

**Comment by amerkoleci** [comment]
Can you update nuget package with 1.2.0 version please?

**Comment by jkoritzinsky** [comment]
Done.

**Comment by amerkoleci** [comment]
Cannot see it (https://www.nuget.org/packages/SharpGen.Runtime.COM)

**Comment by jkoritzinsky** [comment]
My NuGet API key just expired... I'll have to get back to this later.

**Comment by jkoritzinsky** [comment]
Manually pulled down the package from CI and uploaded it.

**Pull request merged**
